export { authRouter } from './auth.routes.js'
export { cartRouter } from './cart.routes.js'
export { categoryRouter } from './category.routes.js'
export { orderRouter } from './order.routes.js'
export { productRouter } from './product.routes.js'
export { reviewRouter } from './review.routes.js'
export { userRouter } from './user.routes.js'
export { wishlistRouter } from './wishlist.routes.js'
